spring.application.name=online-shop

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/online_shop_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=m0pczGQxjMEbDTPHPQ0deKFZio5rfStoT1X0mpXr4cc=
jwt.expiration=3600000
jwt.refresh-expiration=604800000

# Midtrans
midtrans.server-key=SB-Mid-server-K1nXqEJewG-Ks03XS7FNyc0A
midtrans.client-key=SB-Mid-client-MP8TFBx6aCZ4lrzo
midtrans.snap-url=https://app.sandbox.midtrans.com/snap/v1/transactions